variables:
  CI_REGISTRY_USER: "asethdocker"
  CI_REGISTRY_PASSWORD: "Emptyspaces999"
  #CI_REGISTRY_IMAGE: "asethdocker/yb_proxy_auth"
stages:
  - build
  - deploy
docker-build-dev:
    # Official docker image.
    image: docker:latest
    stage: build
    services:
      - docker:dind
    script:
      # - docker stop $(docker ps -aq)
      # - docker rm -f "$CONTAINER_NAME"
      #- docker ps -q -f name="$CONTAINER_NAME" 
     #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
     #- docker build -t "$CI_REGISTRY_IMAGE" .
     - docker-compose -f docker-compose.dev.yml build
     #- docker rm -f "$CONTAINER_NAME" || true
    only:
     - develop 
docker-build-prod:
    # Official docker image.
    image: docker:latest
    stage: build
    services:
      - docker:dind
    script:
      # - docker stop $(docker ps -aq)
      # - docker rm -f "$CONTAINER_NAME"
      #- docker ps -q -f name="$CONTAINER_NAME" 
     #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
     #- docker build -t "$CI_REGISTRY_IMAGE" .
     - docker-compose -f docker-compose.prod.yml build
    only:
     - master
     #- docker rm -f "$CONTAINER_NAME" || true     
docker-deploy-dev:
    stage: deploy
    script:
     #- docker push "$CI_REGISTRY_IMAGE"
     - docker system prune -f 
     - docker-compose -f docker-compose.dev.yml up -d
     - cd
     - docker cp newyb/yb_fashion_image_classifier/vgg19_transfer_subcat1.h5 ms_classifier_dev:/app
     - docker cp newyb/yb_fashion_image_classifier/vgg19_transfer_gendermastercat (1).h5 ms_classifier_dev:/app
     - docker cp newyb/yb_fashion_image_classifier/vgg19_transfer_articletype (1).h5 ms_classifier_dev:/app
     - docker cp newyb/yb_fashion_image_classifier/model_final.pth ms_classifier_dev:/app
    only:
     - develop
  
docker-deploy-prod:
    stage: deploy  
    script:  
     #- docker push "$CI_REGISTRY_IMAGE"
     - docker system prune -f
     - docker-compose -f docker-compose.prod.yml up -d
     - docker cp newyb/yb_fashion_image_classifier/vgg19_transfer_subcat1.h5 ms_classifier_prod:/app
     - docker cp newyb/yb_fashion_image_classifier/vgg19_transfer_gendermastercat (1).h5 ms_classifier_prod:/app
     - docker cp newyb/yb_fashion_image_classifier/vgg19_transfer_articletype (1).h5 ms_classifier_prod:/app
     - docker cp newyb/yb_fashion_image_classifier/model_final.pth ms_classifier_prod:/app
    only:
     - master 